package group04.common.events;

public enum EventType {
    PLAYER_SHOOT_GUN, PLAYER_SHOOT_ROCKET, ENTITY_HIT, ENEMY_SHOOT, PICKUP_WEAPON, DROP_CURRENCY, PICKUP_CURRENCY, PLAYER_SWING, PICKUP_GUN,
    DROP_BOOST, PICKUP_BOOST, ROCKET_HIT, PLATFORM_SPAWN, ENEMY_SWING, PLAYER_DEATH;
}
